site_name: V1 Engineering Inc Docs
site_url: https://docs.v1engineering.com
google_analytics:
  - 'UA-36825469-4'
  - 'auto'
repo_name: V1EngineeringInc/V1EngineeringInc-Docs
repo_url: https://github.com/V1EngineeringInc/V1EngineeringInc-Docs/
edit_uri: 'tree/master/docs/'

nav:
 - New Documents Home: index.md

 - Build:
   - MPCNC: 
     - Basics: mpcnc/index.md
     - Instructions:
       - Table: mpcnc/table.md
       - Conduit: mpcnc/conduit.md
       - Corners, Rollers, Base: mpcnc/base.md
       - Z-Axis: mpcnc/z-axis.md
       - Middle Assembly: mpcnc/middle-assm.md
       - Gantry: mpcnc/gantry.md
       - Final: mpcnc/final.md
       - Belts: mpcnc/belts.md
     - Trouble Shooting: mpcnc/troubleshooting.md
   - LowRider:
     - Assembly: lowrider/index.md
     - Old Version: lowrider/version1.md
   - MP3DP:
     - Main: mp3dp/index.md
     - Old Version: mp3dp/version1.md
   - ZenXY: zenxy/index.md

 - Control:
   - Some Control Board Options:
     - Ultimachine Boards: electronics/ultimachine.md
     - Ramps: electronics/ramps.md
   - Steppers:
     - Wiring The Steppers: electronics/steppers.md
   - Some Advanced Options:
     - v1pi - Headless: electronics/v1pi.md
     - Dual Endstops: electronics/dual-endstops.md

 - Setup:
   - Getting Started: software/index.md

 - Use:    
   - Tools:
     - Milling:
       - Milling Basics: tools/milling-basics.md
       - EstlCAM Setup: software/estlcam-basics.md
       - EstlCAM Intermediate (2.5d): software/estlcam-2p5d.md
     - 3D Printing:
       - Main: tools/import-extruder.md
     - Lasers:
       - Main: tools/lasers.md
       - Engraving Mirrors: tools/laser-engraving-mirrors.md
     - Drag Knife/Vinyl: tools/drag-knife.md
   - Learn:
     - Editing mkdocs: mkdocs_info.md
     - Repetier-Host: software/repetier-host.md
     - Firmware: electronics/marlin-firmware.md
   - Troubleshoot: 
     - Reversing a Stepper: software/reverse-motor.md


theme:
  name: 'material'
  palette:
    primary: 'black'
    accent: 'red'
  logo: "img/favicon.ico"
  favicon: "img/favicon.ico"

extra:
  social:
    - type: 'globe'
      link: 'https://v1engineering.com'
    - type: 'shopping-cart'
      link: 'https://shop.v1engineering.com'

extra_css: [v1.css]

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

copyright: "<a href=\"https://creativecommons.org/licenses/by-sa/4.0/legalcode\">CC-BY-SA</a> Copyright 2019 V1Engineering Inc."

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pyembed.markdown
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.extra
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - sane_lists
  - smarty
  - toc:
      permalink: true
  - lightgallery
  - pymdownx.extra

