site_name: V1 Engineering Documentation
site_url: https://docs.v1engineering.com
google_analytics:
  - 'UA-36825469-4'
  - 'auto'
repo_name: V1EngineeringInc/V1EngineeringInc-Docs
repo_url: https://github.com/V1EngineeringInc/V1EngineeringInc-Docs/
edit_uri: 'edit/master/docs/'

nav:
 - Home: index.md

 - Build:
   - MPCNC:
     - Introduction to The MPCNC: mpcnc/intro.md
     - MPCNC Primo Parts list: mpcnc/PParts.md
     - Calculator: mpcnc/calculator.md
     - 1-Table: mpcnc/Ptable.md
     - 2-Base: mpcnc/Pbase.md
     - 3-Trucks: mpcnc/trucks.md
     - 4-Tops: mpcnc/tops.md
     - 5-Core: mpcnc/core.md
     - 6-Z Axis: mpcnc/PZPage.md
     - 7-Squaring: mpcnc/squaring.md
     - 8-Belts: mpcnc/PBelts.md
     - Trouble Shooting: mpcnc/troubleshooting.md
     - Previous Version:
       - Basics: mpcnc/burly/index.md
       - Parts: mpcnc/burly/parts.md
       - Assembly:
         - Table: mpcnc/burly/table.md
         - Conduit: mpcnc/burly/conduit.md
         - Corners, Rollers, Base: mpcnc/burly/base.md
         - Z-Axis: mpcnc/burly/z-axis.md
         - Middle Assembly: mpcnc/burly/middle-assm.md
         - Gantry: mpcnc/burly/gantry.md
         - Final: mpcnc/burly/final.md
         - Belts: mpcnc/burly/belts.md
   - LowRider:
     - Assembly: lowrider/index.md
     - Calculator: lowrider/calculator.md
     - Old Version: lowrider/version1.md
   - MP3DP:
     - Main: mp3dp/index.md
     - Old Version: mp3dp/version1.md
   - ZenXY: 
     - ZenXY v2: zenxy/index.md
     - ZenXY v2 Build Calculator: Zen2calculator.md
     - Previous Version: zenxy/og_zen.md

 - Control:
   - Some Control Board Options:
     - Ultimachine Boards: electronics/ultimachine.md
     - Ramps: electronics/ramps.md
     - SKR Pro: electronics/skrpro.md
   - Steppers:
     - Wiring The Steppers: electronics/steppers.md
   - Some Advanced Options:
     - v1pi - Headless: electronics/v1pi.md
     - Dual Endstops: electronics/dual-endstops.md
     - Dual Endstops Low Rider: electronics/dual-lr.md
   - Setup: software/index.md

 - Use:
   - Tools:
     - Milling:
       - Milling Basics: tools/milling-basics.md
       - EstlCAM Setup: software/estlcam-basics.md
       - EstlCAM Intermediate (2.5d): software/estlcam-2p5d.md
       - F Engrave V-Carve: software/Fengrave-vcarve-inlay.md
     - 3D Printing:
       - Main: tools/import-extruder.md
     - Lasers:
       - Main: tools/lasers.md
       - Engraving Mirrors: tools/laser-engraving-mirrors.md
     - Drag Knife/Vinyl: tools/drag-knife.md
     - Needle Cutter: tools/foam-needle-cutter.md
   - Troubleshoot:
     - Reversing a Stepper: software/reverse-motor.md

 - Learn:
    - Editing mkdocs: mkdocs_info.md
    - Software Workflow: learn/software_overview.md
    - Repetier-Host: software/repetier-host.md
    - Firmware: electronics/marlin-firmware.md
    - Marlin Releases: electronics/marlin-releases.md
    - PlatformIO: learn/platformio.md
    - G-code: learn/gcode.md
    - Motion: learn/motion.md
    - Coordinates: learn/coordinates.md

theme:
  name: 'material'
  palette:
    primary: 'black'
    accent: 'red'
  features:
  - navigation.tabs
  logo: "img/favicon.ico"
  favicon: "img/favicon.ico"

extra:
  social:
    - type: 'globe'
      link: 'https://v1engineering.com'
    - type: 'shopping-cart'
      link: 'https://shop.v1engineering.com'

extra_css: [v1.css]

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

copyright: "<a href=\"https://creativecommons.org/licenses/by-sa/4.0/legalcode\">CC-BY-SA</a> Copyright 2021 V1Engineering Inc."

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pyembed.markdown
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.extra
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - sane_lists
  - smarty
  - toc:
      permalink: true
  - lightgallery

