site_name: V1 Engineering Inc Docs

repo_url: https://github.com/V1EngineeringInc/V1EngineeringInc-Docs/
edit_uri: 'tree/master/docs/'

theme: 'windmill'
extra_css: [v1.css]

# This doesn't seem to work. It looks like it's abusing the address:
#     404 GET /https://www.v1engineering.com/wp-content/uploads/2017/12/V1-Engineering-logo-260wide.png
# extra:
#   logo: "https://www.v1engineering.com/wp-content/uploads/2017/12/V1-Engineering-logo-260wide.png"

copyright: "<a href=\"https://creativecommons.org/licenses/by-sa/4.0/legalcode\">CC-BY-SA</a> Copyright 2019 V1Engineering Inc."
nav:
 - Index: index.md
 - Editing mkdocs: mkdocs_info.md
 - MPCNC:
     - Assembly:
         - Step1: pg1.md
     - Electronics:
         - Step2: pg2.md
     - Madness: 
         - Laser Stuff: 
            - laser1: pg1.md
            - Laser2: pg2.md
         - Plasma Stuff:
            - plasma3: pg3.md
            - plasma4: pg4.md
 - LowRider:
     - Assembly:
         - Step3: pg3.md
     - Electronics:
         - Step4: pg4.md
