site_name: V1 Engineering Documentation
site_url: https://docs.v1e.com
repo_name: V1EngineeringInc/V1EngineeringInc-Docs
repo_url: https://github.com/V1EngineeringInc/V1EngineeringInc-Docs/
edit_uri: 'edit/master/docs/'

nav:
 - Home: index.md

 - Build:
   - MPCNC:
     - Introduction to The MPCNC: mpcnc/intro.md
     - MPCNC Primo Parts list: mpcnc/PParts.md
     - Calculator: mpcnc/calculator.md
     - 1-Table: mpcnc/Ptable.md
     - 2-Base: mpcnc/Pbase.md
     - 3-Trucks: mpcnc/trucks.md
     - 4-Tops: mpcnc/tops.md
     - 5-Core: mpcnc/core.md
     - 6-Z Axis: mpcnc/PZPage.md
     - 7-Squaring: mpcnc/squaring.md
     - 8-Belts: mpcnc/PBelts.md
     - Trouble Shooting: mpcnc/troubleshooting.md
     - Previous Version -Burly:
       - Basics: mpcnc/burly/index.md
       - Parts: mpcnc/burly/parts.md
       - Assembly:
         - Table: mpcnc/burly/table.md
         - Conduit: mpcnc/burly/conduit.md
         - Corners, Rollers, Base: mpcnc/burly/base.md
         - Z-Axis: mpcnc/burly/z-axis.md
         - Middle Assembly: mpcnc/burly/middle-assm.md
         - Gantry: mpcnc/burly/gantry.md
         - Final: mpcnc/burly/final.md
         - Belts: mpcnc/burly/belts.md
   - LowRider:
     - LowRider CNC V4: lowrider/index.md
     - LowRider V4 Calculator: lowrider/calculator.md
     - Previous Versions:     
       - LowRider CNC V3: lowrider/lowrider3.md
       - LowRider V3 Calculator: lowrider/lr3calculator.md
       - LR2 Assembly: lowrider/lrv2/indexv2.md
       - LR2 Parts: lowrider/lrv2/partsv2.md
       - LR2 Calculator: lowrider/lrv2/calculatorv2.md
       - LR1: lowrider/lrv2/version1.md
   - MP3DP - The Printer:
     - MP3DP v5: mp3dp/index.md
     - Previous Versions:
       - MP3DP v4: mp3dp/mp3dpv4.md
       - MP3DP v3 Parts: mp3dp/version3index.md
       - MP3DP v3 Assembly: mp3dp/version3assm.md
       - MP3DP v2: mp3dp/version2.md
       - MP3DP v1: mp3dp/version1.md
   - ZenXY: 
     - ZenXY v2: zenxy/index.md
     - ZenXY v2 Build Calculator: zenxy/zen2calculator.md
     - ZenXY v2 Assembly: zenxy/zen2assm1.md
     - Previous Version: zenxy/og_zen.md

 - Control:
   - Control Boards:
     - Jackpot CNC Controller: electronics/jackpot.md
     - SKR Pro: electronics/skrpro.md
     - Ultimachine Boards: electronics/ultimachine.md
     - Ramps: electronics/ramps.md
   - Setup: software/index.md
     
 - Use:
   - Tools:
     - Milling:
       - EstlCAM Setup: software/estlcam-basics.md
       - Milling Basics: tools/milling-basics.md
       - "Kiri:Moto Basics": software/kiri.md
       - EstlCAM Intermediate (2.5d): software/estlcam-2p5d.md
       - Inlays: software/Fengrave-vcarve-inlay.md
     - Lasers:
       - Main: tools/lasers.md
       - Engraving Mirrors: tools/laser-engraving-mirrors.md
     - Drag Knife/Vinyl: tools/drag-knife.md
     - Needle Cutter: tools/foam-needle-cutter.md

 - Learn:
    - FAQ's: learn/faq.md
    - Editing mkdocs: mkdocs_info.md
    - Software Workflow: learn/software_overview.md
    - Repetier-Host: software/repetier-host.md
    - Marlin Firmware: electronics/marlin-firmware.md
    - XLoader: electronics/xloader.md
    - PlatformIO: learn/platformio.md
    - Arduino: electronics/arduino.md
    - G-code: learn/gcode.md
    - Motion: learn/motion.md
    - Coordinates: learn/coordinates.md
    - V1pi - Headless: electronics/v1pi.md

 - Archive:
    - Wiring The Steppers: electronics/steppers.md
    - Dual Endstops: electronics/dual-endstops.md
    - Milling Metal: tools/milling-metal.md
    - Import Extruder: tools/import-extruder.md
    - Reversing a Stepper: software/reverse-motor.md

theme:
  font: false
  name: 'material'
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: black
    accent: red
    toggle:
     icon: material/brightness-7
     name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: grey
    accent: red
    toggle:
      icon: material/brightness-4
      name: Switch to light mode    
  features:
  - navigation.tracking
  - navigation.instant
  - navigation.top
  - toc.integrate
  - toc.follow
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.action.edit
  logo: "img/favicon.ico"
  favicon: "img/favicon.ico"

extra:
  social:
    - icon: 'fontawesome/solid/house'
      link: 'https://www.v1e.com'
    - icon: 'fontawesome/solid/cart-plus'
      link: 'https://www.v1e.com/collections.com'
    - icon: 'material/forum'
      link: 'https://forum.v1e.com/'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/V1Engineering'
    - icon: 'fontawesome/brands/facebook'
      link: 'https://www.facebook.com/groups/1156276207801920'
    - icon: 'fontawesome/brands/instagram'
      link: 'https://www.instagram.com/v1engineering/'
    - icon: 'fontawesome/brands/youtube'
      link: 'https://www.youtube.com/channel/UCXf0vDExLLX1lb2cpyiOFbg'
    - icon: 'fontawesome/brands/reddit'
      link: 'https://www.reddit.com/r/mpcnc/'
    - icon: 'fontawesome/brands/discord'
      link: 'https://discord.gg/hMaBvfe'
    - icon: 'fontawesome/brands/patreon'
      link: 'https://www.patreon.com/V1Engineering'

extra_css: 
 - v1.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  
copyright: "<a href=\"https://creativecommons.org/licenses/by-sa/4.0/\">CC-BY-SA</a> Copyright 2024 V1Engineering Inc."

plugins:
  - glightbox
  - search
  - privacy

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.extra
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - sane_lists
  - smarty
  - toc:
      permalink: true
 
